const QUIRK_DUMB = 1
const QUIRK_ALWAYS_UPRIGHT = 2
const QUIRK_TEAR = 4

module.exports.QUIRK_DUMB = QUIRK_DUMB
module.exports.QUIRK_ALWAYS_UPRIGHT = QUIRK_ALWAYS_UPRIGHT
module.exports.QUIRK_TEAR = QUIRK_TEAR
